List<String> symptoms = [
  "Fever",
  "Cough",
  "Fatigue",
  "Headache",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Abdominal pain",
  "Chest pain",
  "Shortness of breath",
  "Muscle weakness",
  "Joint pain",
  "Rash",
  "Swelling",
  "Dizziness",
  "Confusion",
  "Memory loss",
  "Seizures",
  "Difficulty sleeping",
  "Weight loss or gain",
  "Sore throat",
  "Stuffy or runny nose",
  "Sneezing",
  "Chills",
  "Sweating",
  "Back pain",
  "Numbness or tingling",
  "Dry mouth",
  "Frequent urination",
  "Constipation",
  "Heartburn",
  "Itching",
  "Redness",
  "Eye pain",
  "Blurred vision",
  "Fainting",
  "Irritability",
  "Loss of appetite",
  "Swollen lymph nodes",
  "Pale skin",
  "Unexplained bruising",
  "Hair loss",
  "Brittle nails",
  "Toothache",
  "Bleeding gums",
  "Bad breath",
  "Difficulty swallowing",
  "Excessive thirst",
  "Night sweats",
  "Cold hands and feet",
  "Sensitivity to light",
  "Impaired coordination",
  "Tremors",
  "Slurred speech",
  "Difficulty concentrating",
  "Mood swings",
  "Agitation",
  "Suicidal thoughts",
  "Hallucinations",
  "Panic attacks",
  "Racing heartbeat",
  "Erectile dysfunction",
  "Irregular menstrual periods",
  "Painful periods",
  "Infertility",
  "Swollen testicles",
  "Breast lump",
  "Blood in urine",
  "Frequent infections",
  "Rapid weight loss",
  "Yellowing of the skin and eyes",
  "Joint stiffness",
  "Skin ulcers",
  "Wheezing",
  "Swollen ankles",
  "Unexplained weight loss",
  "Excessive hunger",
  "Fatigue after eating",
  "Chronic cough",
  "Blood in stool",
  "Rectal bleeding",
  "Painful urination",
  "Testicular pain",
  "Lower back pain",
  "Swollen tonsils",
  "Cold sores",
  "Chest tightness",
  "Heart palpitations",
  "Muscle cramps",
  "Frequent nosebleeds",
  "Swollen liver",
  "Difficulty walking",
  "Sun sensitivity",
  "Abnormal vaginal bleeding",
  "Impotence",
  "Itchy scalp",
  "Vaginal discharge",
  "Loss of smell or taste",
  "Sudden weight gain",
  "Hoarseness",
  "Sudden vision loss",
  "Dry skin",
  "Rapid breathing",
  "Enlarged lymph nodes",
  "Abnormal bruising",
  "Nail pitting",
  "Bloodshot eyes",
  "Dry eyes",
  "Fluid retention",
  "Weakness on one side of the body",
  "Metallic taste in the mouth",
  "Pale tongue",
  "Difficulty swallowing",
  "Sensitivity to heat or cold",
  "Swollen salivary glands",
  "Lethargy",
  "Rapid heartbeat",
  "Slowed reflexes",
  "Impaired memory",
  "Lack of coordination",
  "Delusions",
  "Suicidal tendencies",
  "Social withdrawal",
  "Aggressive behavior",
  "Inability to focus",
  "Loss of interest in activities",
  "Excessive worry",
  "Compulsive behaviors",
  "Difficulty falling asleep",
  "Excessive sleepiness",
  "Restless legs",
  "Numbness or weakness in the limbs",
  "Difficulty speaking",
  "bladder movements",
  "Loss of balance",
  "Abdominal bloating",
  "Pale gums",
  "Swollen tongue",
  "Brittle bones",
  "Joint deformity",
  "Impaired vision",
  "Increased thirst and hunger",
  "Nausea and vomiting blood",
  "Black or tarry stools",
  "Chest discomfort",
  "Sudden weakness",
  "Difficulty breathing or swallowing",
  "Severe abdominal pain",
  "Seizures or convulsions",
  "Difficulty controlling movements",
  "Extreme sensitivity to touch",
  "Chronic fatigue",
  "Painful intercourse",
  "Painful bowel movements",
  "Rapid or irregular heartbeats",
  "Severe back or neck pain",
  "Loss of consciousness",
  "Slowed breathing",
  "Blood in vomit",
  "Confusion or disorientation",
  "Difficulty speaking",
  "Paralysis or weakness in the face",
  "Severe muscle or joint pain",
  "Severe headaches or migraines",
  "Swelling in the legs or arms",
  "Unsteady gait",
  "Unexplained weight gain",
  "Excessive sweating at night",
  "Persistent coughing up blood",
  "Persistent sore throat",
  "Persistent hoarseness",
  "Persistent diarrhea",
  "Persistent abdominal discomfort",
  "Persistent fatigue",
  "Persistent itching or rash",
  "Persistent unexplained fevers",
  "Persistent unexplained weight loss",
  "bladder habits",
  "Persistent difficulty swallowing",
  "Persistent lumps or swelling",
  "Persistent unexplained pain",
  "Persistent shortness of breath",
  "Bleeding between periods",
  "Severe menstrual cramps",
  "Painful urination in women",
  "Testicular swelling or lump",
  "Erectile dysfunction in men",
  "Unexplained changes in breast shape",
  "Irregular heart rhythms",
  "Chest pressure or discomfort",
  "Excessive urination at night",
  "Bone pain",
  "Abdominal distention",
  "Sensitivity to loud noises",
  "Difficulty hearing",
  "Frequent hiccups",
  "Excessive yawning",
  "Loss of balance"
];
